<?xml version="1.0" encoding="UTF-8"?>
<nhi:FeatureCollection xmlns:nhi="http://www.nhi.nu/gml" xmlns:gml="http://www.opengis.net/gml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" nhiVersion="13" xsi:schemaLocation="http://www.nhi.nu/gml ../nhiFeatureTypes.xsd">
	<gml:boundedBy>
		<gml:null>unknown</gml:null>
	</gml:boundedBy>
	<!-- Gekoppeld aan Brug -->
	<gml:featureMember>
		<nhi:normgeparametriseerdprofiel>
			<nhi:code>ngp1</nhi:code>
			<nhi:statusObject>1</nhi:statusObject>
			<nhi:CREATED_DATE>2001-12-17T09:30:47Z</nhi:CREATED_DATE>
			<nhi:LAST_EDITED_DATE>2001-12-17T09:30:47Z</nhi:LAST_EDITED_DATE>
			<nhi:administratiefgebied>1</nhi:administratiefgebied>
			<nhi:naam>naam</nhi:naam>
			<nhi:hyperlink>http://</nhi:hyperlink>
			<nhi:brugID>b1</nhi:brugID>
			<nhi:bodemhoogtebenedenstrooms>1.0</nhi:bodemhoogtebenedenstrooms>
			<nhi:bodemhoogtebovenstrooms>1.0</nhi:bodemhoogtebovenstrooms>
			<nhi:bodembreedte>1.0</nhi:bodembreedte>
			<nhi:taludhellinglinkerzijde>1.0</nhi:taludhellinglinkerzijde>
			<nhi:taludhellingrechterzijde>1.0</nhi:taludhellingrechterzijde>
			<nhi:hoogteplasbermlinkerzijde>1.0</nhi:hoogteplasbermlinkerzijde>
			<nhi:hoogteplasbermrechterzijde>1.0</nhi:hoogteplasbermrechterzijde>
			<nhi:breedteplasbermlinkerzijde>1.0</nhi:breedteplasbermlinkerzijde>
			<nhi:breedteplasbermrechterzijde>1.0</nhi:breedteplasbermrechterzijde>
			<nhi:taludhellingplasbermlinkerzijde>1.0</nhi:taludhellingplasbermlinkerzijde>
			<nhi:taludhellingplasbermrechterzijde>1.0</nhi:taludhellingplasbermrechterzijde>
			<nhi:hoogteinsteeklinkerzijde>1.0</nhi:hoogteinsteeklinkerzijde>
			<nhi:hoogteinsteekrechterzijde>1.0</nhi:hoogteinsteekrechterzijde>
			<nhi:typeRuwheid>1</nhi:typeRuwheid>
			<nhi:ruwheidLaag>1.0</nhi:ruwheidLaag>
			<nhi:ruwheidHoog>1.0</nhi:ruwheidHoog>
			<gml:lineStringProperty>
				<gml:LineString srsName="EPSG:28992"><gml:coordinates>148838.172,424868.313 148816.766,424795.313 148814.141,424787.125 148822.375,424771.688 148852.5,424718.656 148869,424690.5 148875.781,424679.844</gml:coordinates></gml:LineString>
			</gml:lineStringProperty>
		</nhi:normgeparametriseerdprofiel>
	</gml:featureMember>
	<!-- Gekoppeld aan Hydroobject -->
	<gml:featureMember>
		<nhi:normgeparametriseerdprofiel>
			<nhi:code>ngp2</nhi:code>
			<nhi:statusObject>1</nhi:statusObject>
			<nhi:CREATED_DATE>2001-12-17T09:30:47Z</nhi:CREATED_DATE>
			<nhi:LAST_EDITED_DATE>2001-12-17T09:30:47Z</nhi:LAST_EDITED_DATE>
			<nhi:administratiefgebied>1</nhi:administratiefgebied>
			<nhi:naam>naam</nhi:naam>
			<nhi:hyperlink>http://</nhi:hyperlink>
			<nhi:hydroobjectID>ho1</nhi:hydroobjectID>
			<nhi:bodemhoogtebenedenstrooms>1.0</nhi:bodemhoogtebenedenstrooms>
			<nhi:bodemhoogtebovenstrooms>1.0</nhi:bodemhoogtebovenstrooms>
			<nhi:bodembreedte>1.0</nhi:bodembreedte>
			<nhi:taludhellinglinkerzijde>1.0</nhi:taludhellinglinkerzijde>
			<nhi:taludhellingrechterzijde>1.0</nhi:taludhellingrechterzijde>
			<nhi:hoogteplasbermlinkerzijde>1.0</nhi:hoogteplasbermlinkerzijde>
			<nhi:hoogteplasbermrechterzijde>1.0</nhi:hoogteplasbermrechterzijde>
			<nhi:breedteplasbermlinkerzijde>1.0</nhi:breedteplasbermlinkerzijde>
			<nhi:breedteplasbermrechterzijde>1.0</nhi:breedteplasbermrechterzijde>
			<nhi:taludhellingplasbermlinkerzijde>1.0</nhi:taludhellingplasbermlinkerzijde>
			<nhi:taludhellingplasbermrechterzijde>1.0</nhi:taludhellingplasbermrechterzijde>
			<nhi:hoogteinsteeklinkerzijde>1.0</nhi:hoogteinsteeklinkerzijde>
			<nhi:hoogteinsteekrechterzijde>1.0</nhi:hoogteinsteekrechterzijde>
			<nhi:typeRuwheid>1</nhi:typeRuwheid>
			<nhi:ruwheidLaag>1.0</nhi:ruwheidLaag>
			<nhi:ruwheidHoog>1.0</nhi:ruwheidHoog>
			<gml:lineStringProperty>
				<gml:LineString srsName="EPSG:28992"><gml:coordinates>148838.172,424868.313 148816.766,424795.313 148814.141,424787.125 148822.375,424771.688 148852.5,424718.656 148869,424690.5 148875.781,424679.844</gml:coordinates></gml:LineString>
			</gml:lineStringProperty>
		</nhi:normgeparametriseerdprofiel>
	</gml:featureMember>
	<!-- Gekoppeld aan Stuw -->
	<gml:featureMember>
		<nhi:normgeparametriseerdprofiel>
			<nhi:code>ngp2</nhi:code>
			<nhi:statusObject>1</nhi:statusObject>
			<nhi:CREATED_DATE>2001-12-17T09:30:47Z</nhi:CREATED_DATE>
			<nhi:LAST_EDITED_DATE>2001-12-17T09:30:47Z</nhi:LAST_EDITED_DATE>
			<nhi:administratiefgebied>1</nhi:administratiefgebied>
			<nhi:naam>naam</nhi:naam>
			<nhi:hyperlink>http://</nhi:hyperlink>
			<nhi:stuwID>s1</nhi:stuwID>
			<nhi:bodemhoogtebenedenstrooms>1.0</nhi:bodemhoogtebenedenstrooms>
			<nhi:bodemhoogtebovenstrooms>1.0</nhi:bodemhoogtebovenstrooms>
			<nhi:bodembreedte>1.0</nhi:bodembreedte>
			<nhi:taludhellinglinkerzijde>1.0</nhi:taludhellinglinkerzijde>
			<nhi:taludhellingrechterzijde>1.0</nhi:taludhellingrechterzijde>
			<nhi:hoogteplasbermlinkerzijde>1.0</nhi:hoogteplasbermlinkerzijde>
			<nhi:hoogteplasbermrechterzijde>1.0</nhi:hoogteplasbermrechterzijde>
			<nhi:breedteplasbermlinkerzijde>1.0</nhi:breedteplasbermlinkerzijde>
			<nhi:breedteplasbermrechterzijde>1.0</nhi:breedteplasbermrechterzijde>
			<nhi:taludhellingplasbermlinkerzijde>1.0</nhi:taludhellingplasbermlinkerzijde>
			<nhi:taludhellingplasbermrechterzijde>1.0</nhi:taludhellingplasbermrechterzijde>
			<nhi:hoogteinsteeklinkerzijde>1.0</nhi:hoogteinsteeklinkerzijde>
			<nhi:hoogteinsteekrechterzijde>1.0</nhi:hoogteinsteekrechterzijde>
			<nhi:typeRuwheid>1</nhi:typeRuwheid>
			<nhi:ruwheidLaag>1.0</nhi:ruwheidLaag>
			<nhi:ruwheidHoog>1.0</nhi:ruwheidHoog>
			<gml:lineStringProperty>
				<gml:LineString srsName="EPSG:28992"><gml:coordinates>148838.172,424868.313 148816.766,424795.313 148814.141,424787.125 148822.375,424771.688 148852.5,424718.656 148869,424690.5 148875.781,424679.844</gml:coordinates></gml:LineString>
			</gml:lineStringProperty>
		</nhi:normgeparametriseerdprofiel>
	</gml:featureMember>	
	<!-- Gekoppeld aan Grondwaterkoppellijn -->
	<gml:featureMember>
		<nhi:normgeparametriseerdprofiel>
			<nhi:code>ngp2</nhi:code>
			<nhi:statusObject>1</nhi:statusObject>
			<nhi:CREATED_DATE>2001-12-17T09:30:47Z</nhi:CREATED_DATE>
			<nhi:LAST_EDITED_DATE>2001-12-17T09:30:47Z</nhi:LAST_EDITED_DATE>
			<nhi:administratiefgebied>1</nhi:administratiefgebied>
			<nhi:naam>naam</nhi:naam>
			<nhi:hyperlink>http://</nhi:hyperlink>
			<nhi:grondwaterkoppellijnID>gwkl1</nhi:grondwaterkoppellijnID>
			<nhi:bodemhoogtebenedenstrooms>1.0</nhi:bodemhoogtebenedenstrooms>
			<nhi:bodemhoogtebovenstrooms>1.0</nhi:bodemhoogtebovenstrooms>
			<nhi:bodembreedte>1.0</nhi:bodembreedte>
			<nhi:taludhellinglinkerzijde>1.0</nhi:taludhellinglinkerzijde>
			<nhi:taludhellingrechterzijde>1.0</nhi:taludhellingrechterzijde>
			<nhi:hoogteplasbermlinkerzijde>1.0</nhi:hoogteplasbermlinkerzijde>
			<nhi:hoogteplasbermrechterzijde>1.0</nhi:hoogteplasbermrechterzijde>
			<nhi:breedteplasbermlinkerzijde>1.0</nhi:breedteplasbermlinkerzijde>
			<nhi:breedteplasbermrechterzijde>1.0</nhi:breedteplasbermrechterzijde>
			<nhi:taludhellingplasbermlinkerzijde>1.0</nhi:taludhellingplasbermlinkerzijde>
			<nhi:taludhellingplasbermrechterzijde>1.0</nhi:taludhellingplasbermrechterzijde>
			<nhi:hoogteinsteeklinkerzijde>1.0</nhi:hoogteinsteeklinkerzijde>
			<nhi:hoogteinsteekrechterzijde>1.0</nhi:hoogteinsteekrechterzijde>
			<nhi:typeRuwheid>1</nhi:typeRuwheid>
			<nhi:ruwheidLaag>1.0</nhi:ruwheidLaag>
			<nhi:ruwheidHoog>1.0</nhi:ruwheidHoog>
			<gml:lineStringProperty>
				<gml:LineString srsName="EPSG:28992"><gml:coordinates>148838.172,424868.313 148816.766,424795.313 148814.141,424787.125 148822.375,424771.688 148852.5,424718.656 148869,424690.5 148875.781,424679.844</gml:coordinates></gml:LineString>
			</gml:lineStringProperty>
		</nhi:normgeparametriseerdprofiel>
	</gml:featureMember>		
		<!-- Gekoppeld aan Bodemval -->
	<gml:featureMember>
		<nhi:normgeparametriseerdprofiel>
			<nhi:code>ngp2</nhi:code>
			<nhi:statusObject>1</nhi:statusObject>
			<nhi:CREATED_DATE>2001-12-17T09:30:47Z</nhi:CREATED_DATE>
			<nhi:LAST_EDITED_DATE>2001-12-17T09:30:47Z</nhi:LAST_EDITED_DATE>
			<nhi:administratiefgebied>1</nhi:administratiefgebied>
			<nhi:naam>naam</nhi:naam>
			<nhi:hyperlink>http://</nhi:hyperlink>
			<nhi:bodemvalID>bv1</nhi:bodemvalID>
			<nhi:bodemhoogtebenedenstrooms>1.0</nhi:bodemhoogtebenedenstrooms>
			<nhi:bodemhoogtebovenstrooms>1.0</nhi:bodemhoogtebovenstrooms>
			<nhi:bodembreedte>1.0</nhi:bodembreedte>
			<nhi:taludhellinglinkerzijde>1.0</nhi:taludhellinglinkerzijde>
			<nhi:taludhellingrechterzijde>1.0</nhi:taludhellingrechterzijde>
			<nhi:hoogteplasbermlinkerzijde>1.0</nhi:hoogteplasbermlinkerzijde>
			<nhi:hoogteplasbermrechterzijde>1.0</nhi:hoogteplasbermrechterzijde>
			<nhi:breedteplasbermlinkerzijde>1.0</nhi:breedteplasbermlinkerzijde>
			<nhi:breedteplasbermrechterzijde>1.0</nhi:breedteplasbermrechterzijde>
			<nhi:taludhellingplasbermlinkerzijde>1.0</nhi:taludhellingplasbermlinkerzijde>
			<nhi:taludhellingplasbermrechterzijde>1.0</nhi:taludhellingplasbermrechterzijde>
			<nhi:hoogteinsteeklinkerzijde>1.0</nhi:hoogteinsteeklinkerzijde>
			<nhi:hoogteinsteekrechterzijde>1.0</nhi:hoogteinsteekrechterzijde>
			<nhi:typeRuwheid>1</nhi:typeRuwheid>
			<nhi:ruwheidLaag>1.0</nhi:ruwheidLaag>
			<nhi:ruwheidHoog>1.0</nhi:ruwheidHoog>
			<gml:lineStringProperty>
				<gml:LineString srsName="EPSG:28992"><gml:coordinates>148838.172,424868.313 148816.766,424795.313 148814.141,424787.125 148822.375,424771.688 148852.5,424718.656 148869,424690.5 148875.781,424679.844</gml:coordinates></gml:LineString>
			</gml:lineStringProperty>
		</nhi:normgeparametriseerdprofiel>
	</gml:featureMember>	
</nhi:FeatureCollection>
