<?xml version="1.0" encoding="UTF-8"?>
<nhi:FeatureCollection xmlns:nhi="http://www.nhi.nu/gml" xmlns:gml="http://www.opengis.net/gml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" nhiVersion="13" xsi:schemaLocation="http://www.nhi.nu/gml ../nhiFeatureTypes.xsd">
	<gml:boundedBy>
		<gml:null>unknown</gml:null>
	</gml:boundedBy>
	<!-- Gekoppeld aan afsluitmiddel -->
	<gml:featureMember>
		<nhi:sturing>
			<nhi:code>s1</nhi:code>
			<nhi:statusObject>1</nhi:statusObject>
			<nhi:CREATED_DATE>2001-12-17T09:30:47Z</nhi:CREATED_DATE>
			<nhi:LAST_EDITED_DATE>2001-12-17T09:30:47Z</nhi:LAST_EDITED_DATE>
			<nhi:administratiefgebied>1</nhi:administratiefgebied>
			<nhi:naam>naam</nhi:naam>
			<nhi:hyperlink>http://</nhi:hyperlink>
			<nhi:afsluitmiddelID>am1</nhi:afsluitmiddelID>
			<nhi:indicatieComplexeSturing>1</nhi:indicatieComplexeSturing>
			<nhi:beginPeriode>0101</nhi:beginPeriode>
			<nhi:eindPeriode>0112</nhi:eindPeriode>
			<nhi:doelvariabele>1</nhi:doelvariabele>
			<nhi:doelvariabeleEenheid>1</nhi:doelvariabeleEenheid>
			<nhi:stuurvariabele>1</nhi:stuurvariabele>
			<nhi:typeSturing>1</nhi:typeSturing>
			<nhi:typeController>1</nhi:typeController>
			<nhi:meetlocatieID>ml1</nhi:meetlocatieID>
			<nhi:prioriteit>1</nhi:prioriteit>
		</nhi:sturing>
	</gml:featureMember>
	<!-- Gekoppeld aan pomp -->
	<gml:featureMember>
		<nhi:sturing>
			<nhi:code>s2</nhi:code>
			<nhi:statusObject>1</nhi:statusObject>
			<nhi:CREATED_DATE>2001-12-17T09:30:47Z</nhi:CREATED_DATE>
			<nhi:LAST_EDITED_DATE>2001-12-17T09:30:47Z</nhi:LAST_EDITED_DATE>
			<nhi:administratiefgebied>1</nhi:administratiefgebied>
			<nhi:naam>naam</nhi:naam>
			<nhi:hyperlink>http://</nhi:hyperlink>
			<nhi:pompID>p1</nhi:pompID>
			<nhi:indicatieComplexeSturing>1</nhi:indicatieComplexeSturing>
			<nhi:beginPeriode>0101</nhi:beginPeriode>
			<nhi:eindPeriode>0112</nhi:eindPeriode>
			<nhi:doelvariabele>1</nhi:doelvariabele>
			<nhi:doelvariabeleEenheid>1</nhi:doelvariabeleEenheid>
			<nhi:stuurvariabele>1</nhi:stuurvariabele>
			<nhi:typeSturing>1</nhi:typeSturing>
			<nhi:typeController>1</nhi:typeController>
			<nhi:meetlocatieID>ml1</nhi:meetlocatieID>
			<nhi:prioriteit>1</nhi:prioriteit>
		</nhi:sturing>
	</gml:featureMember>
	<!-- Gekoppeld aan hydraulische randvoorwaarde -->
	<gml:featureMember>
		<nhi:sturing>
			<nhi:code>s2</nhi:code>
			<nhi:statusObject>1</nhi:statusObject>
			<nhi:CREATED_DATE>2001-12-17T09:30:47Z</nhi:CREATED_DATE>
			<nhi:LAST_EDITED_DATE>2001-12-17T09:30:47Z</nhi:LAST_EDITED_DATE>
			<nhi:administratiefgebied>1</nhi:administratiefgebied>
			<nhi:naam>naam</nhi:naam>
			<nhi:hyperlink>http://</nhi:hyperlink>
			<nhi:hydrologischerandvoorwaardeID>hr1</nhi:hydrologischerandvoorwaardeID>
			<nhi:indicatieComplexeSturing>1</nhi:indicatieComplexeSturing>
			<nhi:beginPeriode>0101</nhi:beginPeriode>
			<nhi:eindPeriode>0112</nhi:eindPeriode>
			<nhi:doelvariabele>1</nhi:doelvariabele>
			<nhi:doelvariabeleEenheid>1</nhi:doelvariabeleEenheid>
			<nhi:stuurvariabele>1</nhi:stuurvariabele>
			<nhi:typeSturing>1</nhi:typeSturing>
			<nhi:typeController>1</nhi:typeController>
			<nhi:meetlocatieID>ml1</nhi:meetlocatieID>
			<nhi:prioriteit>1</nhi:prioriteit>
		</nhi:sturing>
	</gml:featureMember>

</nhi:FeatureCollection>
