<?xml version="1.0" encoding="UTF-8"?>
<nhi:FeatureCollection xmlns:nhi="http://www.nhi.nu/gml" xmlns:gml="http://www.opengis.net/gml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" hydamoVersion="13" xsi:schemaLocation="http://www.nhi.nu/gml ../nhiFeatureTypes.xsd">
	<gml:boundedBy>
		<gml:null>unknown</gml:null>
	</gml:boundedBy>
	<gml:featureMember>
		 <nhi:GrondwaterInfoPunt>
			<nhi:code>gip1</nhi:code>
			<nhi:statusObject>1</nhi:statusObject>
			<nhi:CREATED_DATE>2001-12-17T09:30:47Z</nhi:CREATED_DATE>
			<nhi:LAST_EDITED_DATE>2001-12-17T09:30:47Z</nhi:LAST_EDITED_DATE>
			<nhi:administratiefgebied>1</nhi:administratiefgebied>			
			<nhi:grondwaterkoppelpuntID>gkp1</nhi:grondwaterkoppelpuntID>
			<nhi:beginPeriode>0101</nhi:beginPeriode>
			<nhi:eindPeriode>0112</nhi:eindPeriode>
			<nhi:waterstand>1.0</nhi:waterstand>
		</nhi:GrondwaterInfoPunt>
	</gml:featureMember>	
	<gml:featureMember>
		 <nhi:GrondwaterInfoPunt>
			<nhi:code>gip2</nhi:code>
			<nhi:statusObject>1</nhi:statusObject>
			<nhi:CREATED_DATE>2001-12-17T09:30:47Z</nhi:CREATED_DATE>
			<nhi:LAST_EDITED_DATE>2001-12-17T09:30:47Z</nhi:LAST_EDITED_DATE>
			<nhi:administratiefgebied>1</nhi:administratiefgebied>			
			<nhi:grondwaterkoppelpuntID>gkp2</nhi:grondwaterkoppelpuntID>
			<nhi:beginPeriode>0101</nhi:beginPeriode>
			<nhi:eindPeriode>0112</nhi:eindPeriode>
			<nhi:waterstand>1.0</nhi:waterstand>
		</nhi:GrondwaterInfoPunt>
	</gml:featureMember>	
	<gml:featureMember>
		 <nhi:GrondwaterInfoPunt>
			<nhi:code>gip3</nhi:code>
			<nhi:statusObject>1</nhi:statusObject>
			<nhi:CREATED_DATE>2001-12-17T09:30:47Z</nhi:CREATED_DATE>
			<nhi:LAST_EDITED_DATE>2001-12-17T09:30:47Z</nhi:LAST_EDITED_DATE>
			<nhi:administratiefgebied>1</nhi:administratiefgebied>			
			<nhi:grondwaterkoppelpuntID>invalid</nhi:grondwaterkoppelpuntID>
			<nhi:beginPeriode>0101</nhi:beginPeriode>
			<nhi:eindPeriode>0112</nhi:eindPeriode>
			<nhi:waterstand>1.0</nhi:waterstand>
		</nhi:GrondwaterInfoPunt>
	</gml:featureMember>	
</nhi:FeatureCollection>
