<?xml version="1.0" encoding="UTF-8"?>
<nhi:FeatureCollection xmlns:nhi="http://www.nhi.nu/gml" xmlns:gml="http://www.opengis.net/gml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" nhiVersion="13" xsi:schemaLocation="http://www.nhi.nu/gml ../nhiFeatureTypes.xsd">
	<gml:boundedBy>
		<gml:null>unknown</gml:null>
	</gml:boundedBy>
	<gml:featureMember>
		 <nhi:grondwaterinfolijn>
			<nhi:code>gil1</nhi:code>
			<nhi:statusObject>1</nhi:statusObject>
			<nhi:CREATED_DATE>2001-12-17T09:30:47Z</nhi:CREATED_DATE>
			<nhi:LAST_EDITED_DATE>2001-12-17T09:30:47Z</nhi:LAST_EDITED_DATE>
			<nhi:administratiefgebied>1</nhi:administratiefgebied>			
			<nhi:grondwaterkoppellijnID>gwkl1</nhi:grondwaterkoppellijnID>
			<nhi:beginPeriode>0101</nhi:beginPeriode>
			<nhi:eindPeriode>0112</nhi:eindPeriode>
			<nhi:natteOmtrek>1.0</nhi:natteOmtrek>
			<nhi:bodemweerstand>1.0</nhi:bodemweerstand>
			<nhi:infiltratiefactor>1.0</nhi:infiltratiefactor>
			<nhi:bodemBreedte>1.0</nhi:bodemBreedte>
			<nhi:bodemhoogteBovenstrooms>1.0</nhi:bodemhoogteBovenstrooms>
			<nhi:bodemhoogteBenedenstrooms>1.0</nhi:bodemhoogteBenedenstrooms>
			<nhi:flux>1.0</nhi:flux>
		</nhi:grondwaterinfolijn>
	</gml:featureMember>	
	<gml:featureMember>
		 <nhi:grondwaterinfolijn>
			<nhi:code>gil2</nhi:code>
			<nhi:statusObject>1</nhi:statusObject>
			<nhi:CREATED_DATE>2001-12-17T09:30:47Z</nhi:CREATED_DATE>
			<nhi:LAST_EDITED_DATE>2001-12-17T09:30:47Z</nhi:LAST_EDITED_DATE>
			<nhi:administratiefgebied>1</nhi:administratiefgebied>			
			<nhi:grondwaterkoppellijnID>gwkl2</nhi:grondwaterkoppellijnID>
			<nhi:beginPeriode>0101</nhi:beginPeriode>
			<nhi:eindPeriode>0112</nhi:eindPeriode>
			<nhi:natteOmtrek>1.0</nhi:natteOmtrek>
			<nhi:bodemweerstand>1.0</nhi:bodemweerstand>
			<nhi:infiltratiefactor>1.0</nhi:infiltratiefactor>
			<nhi:bodemBreedte>1.0</nhi:bodemBreedte>
			<nhi:bodemhoogteBovenstrooms>1.0</nhi:bodemhoogteBovenstrooms>
			<nhi:bodemhoogteBenedenstrooms>1.0</nhi:bodemhoogteBenedenstrooms>
			<nhi:flux>1.0</nhi:flux>
		</nhi:grondwaterinfolijn>
	</gml:featureMember>	
<gml:featureMember>
		 <nhi:grondwaterinfolijn>
			<nhi:code>gil3</nhi:code>
			<nhi:statusObject>1</nhi:statusObject>
			<nhi:CREATED_DATE>2001-12-17T09:30:47Z</nhi:CREATED_DATE>
			<nhi:LAST_EDITED_DATE>2001-12-17T09:30:47Z</nhi:LAST_EDITED_DATE>
			<nhi:administratiefgebied>1</nhi:administratiefgebied>			
			<nhi:grondwaterkoppellijnID>invalid</nhi:grondwaterkoppellijnID>
			<nhi:beginPeriode>0101</nhi:beginPeriode>
			<nhi:eindPeriode>0112</nhi:eindPeriode>
			<nhi:natteOmtrek>1.0</nhi:natteOmtrek>
			<nhi:bodemweerstand>1.0</nhi:bodemweerstand>
			<nhi:infiltratiefactor>1.0</nhi:infiltratiefactor>
			<nhi:bodemBreedte>1.0</nhi:bodemBreedte>
			<nhi:bodemhoogteBovenstrooms>1.0</nhi:bodemhoogteBovenstrooms>
			<nhi:bodemhoogteBenedenstrooms>1.0</nhi:bodemhoogteBenedenstrooms>
			<nhi:flux>1.0</nhi:flux>
		</nhi:grondwaterinfolijn>
	</gml:featureMember>	
</nhi:FeatureCollection>
