<?xml version="1.0" encoding="UTF-8"?>
<nhi:FeatureCollection xmlns:nhi="http://www.nhi.nu/gml" xmlns:gml="http://www.opengis.net/gml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" hydamoVersion="13" xsi:schemaLocation="http://www.nhi.nu/gml ../nhiFeatureTypes.xsd">
	<gml:boundedBy>
		<gml:null>unknown</gml:null>
	</gml:boundedBy>
	<gml:featureMember>
		<nhi:Streefpeil>
			<nhi:code>sp1</nhi:code>
			<nhi:statusObject>1</nhi:statusObject>
			<nhi:CREATED_DATE>2001-12-17T09:30:47Z</nhi:CREATED_DATE>
			<nhi:LAST_EDITED_DATE>2001-12-17T09:30:47Z</nhi:LAST_EDITED_DATE>
			<nhi:administratiefgebied>1</nhi:administratiefgebied>
			<nhi:soortStreefpeil>1</nhi:soortStreefpeil>
			<nhi:waterhoogte>1.0</nhi:waterhoogte>
			<nhi:beginPeriode>0101</nhi:beginPeriode>
			<nhi:eindPeriode>0112</nhi:eindPeriode>
			<nhi:peilgebiedpraktijkID>pgp1</nhi:peilgebiedpraktijkID>
			<nhi:peilafwijkinggebiedID>pag1</nhi:peilafwijkinggebiedID>
		</nhi:Streefpeil>
	</gml:featureMember>
	<gml:featureMember>
		<nhi:Streefpeil>
			<nhi:code>sp2</nhi:code>
			<nhi:statusObject>1</nhi:statusObject>
			<nhi:CREATED_DATE>2001-12-17T09:30:47Z</nhi:CREATED_DATE>
			<nhi:LAST_EDITED_DATE>2001-12-17T09:30:47Z</nhi:LAST_EDITED_DATE>
			<nhi:administratiefgebied>1</nhi:administratiefgebied>
			<nhi:soortStreefpeil>1</nhi:soortStreefpeil>
			<nhi:waterhoogte>1.0</nhi:waterhoogte>
			<nhi:beginPeriode>0101</nhi:beginPeriode>
			<nhi:eindPeriode>0112</nhi:eindPeriode>
			<nhi:peilgebiedpraktijkID>pgp1</nhi:peilgebiedpraktijkID>
			<nhi:peilafwijkinggebiedID>pag1</nhi:peilafwijkinggebiedID>
		</nhi:Streefpeil>
	</gml:featureMember>
</nhi:FeatureCollection>
